------------------------------------------------------------
-- Tabla nueva para Experiencia 3 Semana 8 (distinta a sumativas anteriores)
------------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE GUIAS_DESPACHO_S8 CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE GUIAS_DESPACHO_S8 (
  ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  MESSAGE_ID      VARCHAR2(36)  NOT NULL,
  TIPO_OPERACION  VARCHAR2(20)  NOT NULL,
  PEDIDO_ID       VARCHAR2(20),
  CLIENTE         VARCHAR2(100),
  DIRECCION       VARCHAR2(200),
  DESCRIPCION     VARCHAR2(500),
  TRANSPORTISTA   VARCHAR2(100),
  FECHA           VARCHAR2(20),
  S3_KEY          VARCHAR2(300),
  NOMBRE_GUIA     VARCHAR2(100),
  ESTADO          VARCHAR2(20)  DEFAULT 'PROCESADO' NOT NULL,
  FECHA_REGISTRO  TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT UK_GUIAS_S8_MESSAGE_ID UNIQUE (MESSAGE_ID)
);

CREATE INDEX IDX_GUIAS_S8_S3_KEY ON GUIAS_DESPACHO_S8 (S3_KEY);
CREATE INDEX IDX_GUIAS_S8_PEDIDO ON GUIAS_DESPACHO_S8 (PEDIDO_ID);
