spring.application.name=empresa-transportista-consumer
server.port=8081

aws.s3.bucket=${AWS_S3_BUCKET:tu-bucket-guias}
efs.path=${EFS_PATH:/app/efs}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

spring.datasource.url=${DB_JDBC_URL:jdbc:postgresql://localhost:5432/guias_db}
spring.datasource.username=${DB_USER:guias}
spring.datasource.password=${DB_PASSWORD:guias_secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.software.amazon.awssdk=INFO

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://empresatransportistaefs.b2clogin.com/tfp/972f25cf-cd03-4c70-84ea-285778b48398/b2c_1_cdy2204-1/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://empresatransportistaefs.b2clogin.com/empresatransportistaefs.onmicrosoft.com/B2C_1_cdy2204-1/discovery/v2.0/keys
spring.security.oauth2.resourceserver.jwt.audiences=49f4ab51-5e0e-4139-9cf4-15f566581b07,https://EmpresaTransportistaEFS.onmicrosoft.com/49f4ab51-5e0e-4139-9cf4-15f566581b07/cdy2204-1
